Created state for filters
CodeYourFuture/ldn8-horizon-chatterbox-talent pull request #38
Opened 2022-07-12 19:35 UTC by pigos4

2022-07-12 19:50 UTC, RitaGlushkova approved these changes
Just need to tidy up a little. Well done!

2022-07-13 08:32 UTC, RitaGlushkova approved these changes

2022-07-13 09:25 UTC, RitaGlushkova requested changes
@pigos4  I tested the filters state functionality and it seems to be working one click late.
For example, if I add `onSite, Hybrid and Remote` options it shows `onSite, Hybrid` and only when I click on the next option (let's say `HR`), then it shows `onSite, Hybrid and Remote` but no `HR`. So it is always one click late.

2022-07-13 17:28 UTC, RitaGlushkova approved these changes

2022-07-13 17:32 UTC, craig-dsilva approved these changes
Good job adding the prettier config

2022-07-13 17:33 UTC, merged